//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3074.
// 
#pragma warning disable 1591

namespace TemplateManager.Services {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TemplateManagerSkillDataServiceBinding", Namespace="urn:TemplateManagerSkillDataService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SkillType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Skill))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Profession))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Campaign))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Attribute))]
    public partial class TemplateManagerSkillDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampaignsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProfessionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSkillsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSkillTypesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TemplateManagerSkillDataService() {
            this.Url = global::TemplateManager.Properties.Settings.Default.TemplateManager_AssetBuilder_localhost_TemplateManagerSkillDataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAttributesCompletedEventHandler GetAttributesCompleted;
        
        /// <remarks/>
        public event GetCampaignsCompletedEventHandler GetCampaignsCompleted;
        
        /// <remarks/>
        public event GetProfessionsCompletedEventHandler GetProfessionsCompleted;
        
        /// <remarks/>
        public event GetSkillsCompletedEventHandler GetSkillsCompleted;
        
        /// <remarks/>
        public event GetSkillTypesCompletedEventHandler GetSkillTypesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TemplateManagerSkillDataServiceAction", RequestNamespace="urn:TemplateManagerSkillDataService", ResponseNamespace="urn:TemplateManagerSkillDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("Attributes")]
        public Attribute[] GetAttributes() {
            object[] results = this.Invoke("GetAttributes", new object[0]);
            return ((Attribute[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAttributesAsync() {
            this.GetAttributesAsync(null);
        }
        
        /// <remarks/>
        public void GetAttributesAsync(object userState) {
            if ((this.GetAttributesOperationCompleted == null)) {
                this.GetAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttributesOperationCompleted);
            }
            this.InvokeAsync("GetAttributes", new object[0], this.GetAttributesOperationCompleted, userState);
        }
        
        private void OnGetAttributesOperationCompleted(object arg) {
            if ((this.GetAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttributesCompleted(this, new GetAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TemplateManagerSkillDataServiceAction", RequestNamespace="urn:TemplateManagerSkillDataService", ResponseNamespace="urn:TemplateManagerSkillDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("Campaigns")]
        public Campaign[] GetCampaigns() {
            object[] results = this.Invoke("GetCampaigns", new object[0]);
            return ((Campaign[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCampaignsAsync() {
            this.GetCampaignsAsync(null);
        }
        
        /// <remarks/>
        public void GetCampaignsAsync(object userState) {
            if ((this.GetCampaignsOperationCompleted == null)) {
                this.GetCampaignsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampaignsOperationCompleted);
            }
            this.InvokeAsync("GetCampaigns", new object[0], this.GetCampaignsOperationCompleted, userState);
        }
        
        private void OnGetCampaignsOperationCompleted(object arg) {
            if ((this.GetCampaignsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampaignsCompleted(this, new GetCampaignsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TemplateManagerSkillDataServiceAction", RequestNamespace="urn:TemplateManagerSkillDataService", ResponseNamespace="urn:TemplateManagerSkillDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("Professions")]
        public Profession[] GetProfessions() {
            object[] results = this.Invoke("GetProfessions", new object[0]);
            return ((Profession[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProfessionsAsync() {
            this.GetProfessionsAsync(null);
        }
        
        /// <remarks/>
        public void GetProfessionsAsync(object userState) {
            if ((this.GetProfessionsOperationCompleted == null)) {
                this.GetProfessionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfessionsOperationCompleted);
            }
            this.InvokeAsync("GetProfessions", new object[0], this.GetProfessionsOperationCompleted, userState);
        }
        
        private void OnGetProfessionsOperationCompleted(object arg) {
            if ((this.GetProfessionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfessionsCompleted(this, new GetProfessionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TemplateManagerSkillDataServiceAction", RequestNamespace="urn:TemplateManagerSkillDataService", ResponseNamespace="urn:TemplateManagerSkillDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("Skills")]
        public Skill[] GetSkills() {
            object[] results = this.Invoke("GetSkills", new object[0]);
            return ((Skill[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSkillsAsync() {
            this.GetSkillsAsync(null);
        }
        
        /// <remarks/>
        public void GetSkillsAsync(object userState) {
            if ((this.GetSkillsOperationCompleted == null)) {
                this.GetSkillsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSkillsOperationCompleted);
            }
            this.InvokeAsync("GetSkills", new object[0], this.GetSkillsOperationCompleted, userState);
        }
        
        private void OnGetSkillsOperationCompleted(object arg) {
            if ((this.GetSkillsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSkillsCompleted(this, new GetSkillsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TemplateManagerSkillDataServiceAction", RequestNamespace="urn:TemplateManagerSkillDataService", ResponseNamespace="urn:TemplateManagerSkillDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("SkillTypes")]
        public SkillType[] GetSkillTypes() {
            object[] results = this.Invoke("GetSkillTypes", new object[0]);
            return ((SkillType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSkillTypesAsync() {
            this.GetSkillTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetSkillTypesAsync(object userState) {
            if ((this.GetSkillTypesOperationCompleted == null)) {
                this.GetSkillTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSkillTypesOperationCompleted);
            }
            this.InvokeAsync("GetSkillTypes", new object[0], this.GetSkillTypesOperationCompleted, userState);
        }
        
        private void OnGetSkillTypesOperationCompleted(object arg) {
            if ((this.GetSkillTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSkillTypesCompleted(this, new GetSkillTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TemplateManagerSkillDataService")]
    public partial class Attribute {
        
        private int idField;
        
        private string nameField;
        
        private int professionField;
        
        private bool isPrimaryField;
        
        private int attributeIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Profession {
            get {
                return this.professionField;
            }
            set {
                this.professionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPrimary {
            get {
                return this.isPrimaryField;
            }
            set {
                this.isPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public int AttributeId {
            get {
                return this.attributeIdField;
            }
            set {
                this.attributeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TemplateManagerSkillDataService")]
    public partial class SkillType {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TemplateManagerSkillDataService")]
    public partial class Skill {
        
        private int idField;
        
        private int skillIdField;
        
        private int campaignField;
        
        private int professionField;
        
        private int attributeField;
        
        private int skillTypeField;
        
        private float energyCostField;
        
        private float castingTimeField;
        
        private float rechargeTimeField;
        
        private float adrenalineCostField;
        
        private float healthSacrificeField;
        
        private float energyRegenField;
        
        private bool isEliteField;
        
        private bool pveOnlyField;
        
        private bool pvpVersionField;
        
        private bool monsterOnlyField;
        
        private string nameField;
        
        private string imageField;
        
        private string tagsField;
        
        private string wikiLinkField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int SkillId {
            get {
                return this.skillIdField;
            }
            set {
                this.skillIdField = value;
            }
        }
        
        /// <remarks/>
        public int Campaign {
            get {
                return this.campaignField;
            }
            set {
                this.campaignField = value;
            }
        }
        
        /// <remarks/>
        public int Profession {
            get {
                return this.professionField;
            }
            set {
                this.professionField = value;
            }
        }
        
        /// <remarks/>
        public int Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        public int SkillType {
            get {
                return this.skillTypeField;
            }
            set {
                this.skillTypeField = value;
            }
        }
        
        /// <remarks/>
        public float EnergyCost {
            get {
                return this.energyCostField;
            }
            set {
                this.energyCostField = value;
            }
        }
        
        /// <remarks/>
        public float CastingTime {
            get {
                return this.castingTimeField;
            }
            set {
                this.castingTimeField = value;
            }
        }
        
        /// <remarks/>
        public float RechargeTime {
            get {
                return this.rechargeTimeField;
            }
            set {
                this.rechargeTimeField = value;
            }
        }
        
        /// <remarks/>
        public float AdrenalineCost {
            get {
                return this.adrenalineCostField;
            }
            set {
                this.adrenalineCostField = value;
            }
        }
        
        /// <remarks/>
        public float HealthSacrifice {
            get {
                return this.healthSacrificeField;
            }
            set {
                this.healthSacrificeField = value;
            }
        }
        
        /// <remarks/>
        public float EnergyRegen {
            get {
                return this.energyRegenField;
            }
            set {
                this.energyRegenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsElite {
            get {
                return this.isEliteField;
            }
            set {
                this.isEliteField = value;
            }
        }
        
        /// <remarks/>
        public bool PveOnly {
            get {
                return this.pveOnlyField;
            }
            set {
                this.pveOnlyField = value;
            }
        }
        
        /// <remarks/>
        public bool PvpVersion {
            get {
                return this.pvpVersionField;
            }
            set {
                this.pvpVersionField = value;
            }
        }
        
        /// <remarks/>
        public bool MonsterOnly {
            get {
                return this.monsterOnlyField;
            }
            set {
                this.monsterOnlyField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public string WikiLink {
            get {
                return this.wikiLinkField;
            }
            set {
                this.wikiLinkField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TemplateManagerSkillDataService")]
    public partial class Profession {
        
        private int idField;
        
        private string nameField;
        
        private int professionIdField;
        
        private bool validPrimaryField;
        
        private bool validSecondaryField;
        
        private string imageField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ProfessionId {
            get {
                return this.professionIdField;
            }
            set {
                this.professionIdField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidPrimary {
            get {
                return this.validPrimaryField;
            }
            set {
                this.validPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidSecondary {
            get {
                return this.validSecondaryField;
            }
            set {
                this.validSecondaryField = value;
            }
        }
        
        /// <remarks/>
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TemplateManagerSkillDataService")]
    public partial class Campaign {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetAttributesCompletedEventHandler(object sender, GetAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Attribute[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Attribute[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetCampaignsCompletedEventHandler(object sender, GetCampaignsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampaignsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampaignsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Campaign[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Campaign[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetProfessionsCompletedEventHandler(object sender, GetProfessionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfessionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfessionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Profession[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Profession[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetSkillsCompletedEventHandler(object sender, GetSkillsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSkillsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSkillsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Skill[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Skill[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetSkillTypesCompletedEventHandler(object sender, GetSkillTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSkillTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSkillTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SkillType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SkillType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591