//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateManager.Modules.Services.RemoteServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:TemplateManagerService", ConfigurationName="RemoteServices.TemplateManagerServicePort")]
    internal interface TemplateManagerServicePort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TemplateManagerServiceAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="VersionInfo")]
        TemplateManager.Modules.Services.RemoteServices.VersionInfo GetLatestVersion();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TemplateManagerService")]
    public partial class VersionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int majorField;
        
        private int minorField;
        
        private int buildField;
        
        private int revisionField;
        
        private string configurationField;
        
        private string labelField;
        
        private string downloadUrlField;
        
        private string informationUrlField;
        
        /// <remarks/>
        public int Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
                this.RaisePropertyChanged("Major");
            }
        }
        
        /// <remarks/>
        public int Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
                this.RaisePropertyChanged("Minor");
            }
        }
        
        /// <remarks/>
        public int Build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
                this.RaisePropertyChanged("Build");
            }
        }
        
        /// <remarks/>
        public int Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("Revision");
            }
        }
        
        /// <remarks/>
        public string Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
                this.RaisePropertyChanged("Configuration");
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        public string DownloadUrl {
            get {
                return this.downloadUrlField;
            }
            set {
                this.downloadUrlField = value;
                this.RaisePropertyChanged("DownloadUrl");
            }
        }
        
        /// <remarks/>
        public string InformationUrl {
            get {
                return this.informationUrlField;
            }
            set {
                this.informationUrlField = value;
                this.RaisePropertyChanged("InformationUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal interface TemplateManagerServicePortChannel : TemplateManager.Modules.Services.RemoteServices.TemplateManagerServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal partial class TemplateManagerServicePortClient : System.ServiceModel.ClientBase<TemplateManager.Modules.Services.RemoteServices.TemplateManagerServicePort>, TemplateManager.Modules.Services.RemoteServices.TemplateManagerServicePort {
        
        public TemplateManagerServicePortClient() {
        }
        
        public TemplateManagerServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemplateManagerServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateManagerServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateManagerServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TemplateManager.Modules.Services.RemoteServices.VersionInfo GetLatestVersion() {
            return base.Channel.GetLatestVersion();
        }
    }
}
